TRAINING_EXAMPLES = [
    ('hello', 'greeting'),
    ('hi doctor', 'greeting'),
    ('namaste', 'greeting'),
    ('வணக்கம்', 'greeting'),
    ('எனக்கு காய்ச்சல் உள்ளது', 'fever'),
    ('I have a fever', 'fever'),
    ('mujhe bukhar hai', 'fever'),
    ('मुझे बुखार है', 'fever'),
    ('fever body pain and weakness', 'fever'),
    ('காய்ச்சல் உடல் வலி தலைவலி', 'fever'),
    ('cough and sore throat', 'cough'),
    ('I keep coughing at night', 'cough'),
    ('mujhe khansi ho rahi hai', 'cough'),
    ('खांसी और गले में दर्द', 'cough'),
    ('இருமல் மற்றும் தொண்டை வலி', 'cough'),
    ('persistent dry cough', 'cough'),
    ('stomach pain and nausea', 'stomach_pain'),
    ('abdomen hurts and I feel like vomiting', 'stomach_pain'),
    ('pet dard aur ulti', 'stomach_pain'),
    ('पेट दर्द और उल्टी', 'stomach_pain'),
    ('வயிற்று வலி மற்றும் வாந்தி', 'stomach_pain'),
    ('loose motion and stomach ache', 'stomach_pain'),
    ('headache and dizziness', 'headache'),
    ('I feel weak and dizzy', 'headache'),
    ('sir dard ho raha hai', 'headache'),
    ('सिर दर्द और चक्कर', 'headache'),
    ('தலைவலி மற்றும் மயக்கம்', 'headache'),
    ('throbbing headache after screen time', 'headache'),
    ('dizziness and weakness', 'dizziness'),
    ('I feel faint when standing', 'dizziness'),
    ('chakkar aa raha hai', 'dizziness'),
    ('मुझे चक्कर आ रहे हैं', 'dizziness'),
    ('மயக்கம் மற்றும் பலவீனம்', 'dizziness'),
    ('feeling lightheaded and tired', 'dizziness'),
    ('chest pain and shortness of breath', 'chest_pain'),
    ('tightness in chest when walking', 'chest_pain'),
    ('severe pressure in chest', 'chest_pain'),
    ('நெஞ்சு வலி மற்றும் மூச்சுத்திணறல்', 'chest_pain'),
    ('सीने में दर्द और सांस लेने में दिक्कत', 'chest_pain'),
    ('urgent breathing problem', 'emergency'),
    ('I cannot breathe properly', 'emergency'),
    ('endha alavukku serious ah irukku', 'emergency'),
    ('நான் மூச்சு விட முடியவில்லை', 'emergency'),
    ('मुझे सांस लेने में बहुत परेशानी हो रही है', 'emergency'),
    ('seizure and loss of consciousness', 'emergency'),
    ('need health advice', 'general'),
    ('I do not know what is wrong', 'general'),
    ('please help me understand my symptoms', 'general'),
    ('எனக்கு உடல்நலம் குறித்து ஆலோசனை வேண்டும்', 'general'),
    ('मुझे स्वास्थ्य सलाह चाहिए', 'general'),
]

INTENT_PROFILES = {
    'greeting': {
        'title': 'Welcome',
        'summary': 'Tell me your symptoms, how long they have been happening, and whether anything feels severe.',
        'possible_causes': ['No symptoms entered yet'],
        'precautions': ['Share symptoms clearly', 'Mention duration', 'Mention fever, pain, or breathing trouble if present'],
        'next_steps': 'Send a symptom description and I will analyze it.',
        'urgent': False,
    },
    'fever': {
        'title': 'Possible fever or viral infection',
        'summary': 'Your symptoms look similar to a fever or common viral illness pattern.',
        'possible_causes': ['viral infection', 'seasonal flu', 'dehydration'],
        'precautions': ['rest', 'drink fluids', 'monitor temperature', 'avoid self-medicating without advice'],
        'next_steps': 'If the fever stays high, lasts more than two days, or breathing worsens, see a doctor.',
        'urgent': False,
    },
    'cough': {
        'title': 'Respiratory symptom pattern',
        'summary': 'The input suggests a cough or throat-related problem.',
        'possible_causes': ['viral cold', 'throat irritation', 'allergy'],
        'precautions': ['stay hydrated', 'rest your voice', 'avoid smoke and dust', 'wear a mask if needed'],
        'next_steps': 'If coughing becomes severe, lasts more than a week, or you develop breathing issues, consult a clinician.',
        'urgent': False,
    },
    'stomach_pain': {
        'title': 'Digestive discomfort',
        'summary': 'The symptoms point to a stomach or digestive issue.',
        'possible_causes': ['indigestion', 'gastric upset', 'mild food poisoning'],
        'precautions': ['sip water', 'eat light meals', 'avoid oily food', 'rest'],
        'next_steps': 'If the pain becomes intense, persistent, or you cannot keep fluids down, seek medical care.',
        'urgent': False,
    },
    'headache': {
        'title': 'Headache or dehydration pattern',
        'summary': 'This looks like a headache with possible dehydration or fatigue.',
        'possible_causes': ['dehydration', 'lack of sleep', 'stress', 'eye strain'],
        'precautions': ['drink water', 'rest in a quiet place', 'reduce screen time', 'avoid sudden standing'],
        'next_steps': 'If the headache is severe, unusual, or linked to vomiting or vision changes, get checked by a doctor.',
        'urgent': False,
    },
    'dizziness': {
        'title': 'Dizziness or weakness pattern',
        'summary': 'The message suggests dizziness, weakness, or lightheadedness.',
        'possible_causes': ['low fluids', 'low blood sugar', 'fatigue', 'sudden blood pressure change'],
        'precautions': ['sit or lie down', 'drink water', 'eat something light', 'stand up slowly'],
        'next_steps': 'If you faint, feel confused, or symptoms repeat often, get medical help.',
        'urgent': False,
    },
    'chest_pain': {
        'title': 'Possible emergency symptoms',
        'summary': 'Chest discomfort or breathing symptoms can be serious.',
        'possible_causes': ['cardiac concern', 'respiratory distress', 'severe anxiety'],
        'precautions': ['stop activity', 'sit upright', 'call for help', 'do not ignore worsening pain'],
        'next_steps': 'Seek urgent medical attention immediately, especially if the pain is severe or persistent.',
        'urgent': True,
    },
    'emergency': {
        'title': 'Emergency symptoms',
        'summary': 'The input includes warning signs that may need urgent care.',
        'possible_causes': ['serious respiratory issue', 'cardiac problem', 'other urgent medical condition'],
        'precautions': ['call emergency services', 'do not delay', 'sit or lie down safely', 'ask someone nearby for help'],
        'next_steps': 'Please seek immediate emergency medical care now.',
        'urgent': True,
    },
    'general': {
        'title': 'General symptom guidance',
        'summary': 'I need a little more detail to narrow this down.',
        'possible_causes': ['mild illness', 'dehydration', 'temporary irritation'],
        'precautions': ['share the main symptom', 'mention duration', 'mention any fever or breathing trouble'],
        'next_steps': 'Add more detail such as fever, pain location, or how long the symptoms have lasted.',
        'urgent': False,
    },
}

LANGUAGE_PREFIX = {
    'en': 'Detected language: English.',
    'ta': 'கண்டறியப்பட்ட மொழி: தமிழ்.',
    'hi': 'पहचानी गई भाषा: हिंदी।',
}

LANGUAGE_NAMES = {
    'en': 'English',
    'ta': 'Tamil',
    'hi': 'Hindi',
}

LOCALIZED_INTENT_PROFILES = {
    'en': INTENT_PROFILES,
    'ta': {
        'greeting': {
            'title': 'வரவேற்கிறேன்',
            'summary': 'உங்களின் அறிகுறிகள், எத்தனை நாட்களாக உள்ளது, எது அதிகமாக பாதிக்கிறது என்பதைக் கூறுங்கள்.',
            'possible_causes': ['இன்னும் அறிகுறி தரப்படவில்லை'],
            'precautions': ['அறிகுறிகளை தெளிவாக எழுதுங்கள்', 'நாட்கள் எண்ணிக்கையை கூறுங்கள்', 'காய்ச்சல் அல்லது மூச்சுத்திணறல் இருந்தால் குறிப்பிடுங்கள்'],
            'next_steps': 'ஒரு அறிகுறி செய்தி அனுப்புங்கள்; நான் பகுப்பாய்வு செய்கிறேன்.',
            'urgent': False,
        },
        'fever': {
            'title': 'காய்ச்சல் அல்லது வைரஸ் பாதிப்பு இருக்கலாம்',
            'summary': 'இந்த அறிகுறிகள் காய்ச்சல் அல்லது சாதாரண வைரஸ் நோயுடன் பொருந்துகிறது.',
            'possible_causes': ['வைரஸ் தொற்று', 'சீசனல் ஃப்ளூ', 'நீர்ச்சத்து குறைவு'],
            'precautions': ['ஓய்வு எடுக்கவும்', 'தண்ணீர் அதிகம் குடிக்கவும்', 'வெப்பநிலையை கண்காணிக்கவும்', 'மருத்துவர் ஆலோசனையின்றி மருந்து தவிர்க்கவும்'],
            'next_steps': 'காய்ச்சல் 2 நாட்களுக்கு மேல் நீடித்தாலோ அல்லது மூச்சு சிரமம் இருந்தாலோ மருத்துவரை அணுகவும்.',
            'urgent': False,
        },
        'cough': {
            'title': 'இருமல் தொடர்பான அறிகுறி',
            'summary': 'இது இருமல் அல்லது தொண்டை எரிச்சல் பிரச்சனை போல தெரிகிறது.',
            'possible_causes': ['வைரஸ் சளி', 'தொண்டை எரிச்சல்', 'அலெர்ஜி'],
            'precautions': ['நீர்ச்சத்து வைத்துக்கொள்ளவும்', 'குரல் ஓய்வு தரவும்', 'புகை மற்றும் தூசி தவிர்க்கவும்', 'தேவைப்பட்டால் மாஸ்க் அணியவும்'],
            'next_steps': 'இருமல் தீவிரமாவதோ அல்லது ஒரு வாரத்திற்கும் மேல் நீடித்தாலோ மருத்துவரை காணவும்.',
            'urgent': False,
        },
        'stomach_pain': {
            'title': 'செரிமான பிரச்சனை இருக்கலாம்',
            'summary': 'அறிகுறிகள் வயிற்று அல்லது செரிமான சிரமத்தை காட்டுகிறது.',
            'possible_causes': ['செரிமானக்கேடு', 'காஸ்ட்ரிக் எரிச்சல்', 'மிதமான உணவு விஷச்சத்து'],
            'precautions': ['சிறுசிறு தண்ணீர் குடிக்கவும்', 'லேசான உணவு சாப்பிடவும்', 'எண்ணெய் உணவு தவிர்க்கவும்', 'ஓய்வு எடுக்கவும்'],
            'next_steps': 'வலி அதிகரித்தாலோ, நீடித்தாலோ அல்லது வாந்தி காரணமாக தண்ணீர் குடிக்க முடியாவிட்டாலோ உடனே மருத்துவரை அணுகவும்.',
            'urgent': False,
        },
        'headache': {
            'title': 'தலைவலி அல்லது நீர்ச்சத்து குறைவு மாதிரி',
            'summary': 'இந்த அறிகுறிகள் தலைவலி, சோர்வு அல்லது நீர்ச்சத்து குறைவுடன் தொடர்பாக இருக்கலாம்.',
            'possible_causes': ['நீர்ச்சத்து குறைவு', 'தூக்கமின்மை', 'மனஅழுத்தம்', 'கண் சோர்வு'],
            'precautions': ['தண்ணீர் குடிக்கவும்', 'அமைதியான இடத்தில் ஓய்வெடுக்கவும்', 'திரை நேரம் குறைக்கவும்', 'திடீர் எழுச்சி தவிர்க்கவும்'],
            'next_steps': 'தலைவலி கடுமையாக இருந்தாலோ, புதிதாக இருந்தாலோ அல்லது வாந்தி/கண் மங்குதல் இருந்தாலோ மருத்துவரை அணுகவும்.',
            'urgent': False,
        },
        'dizziness': {
            'title': 'மயக்கம் அல்லது பலவீனம் மாதிரி',
            'summary': 'அறிகுறிகள் மயக்கம் அல்லது பலவீனத்தை குறிக்கிறது.',
            'possible_causes': ['நீர்ச்சத்து குறைவு', 'சர்க்கரை குறைவு', 'சோர்வு', 'இரத்த அழுத்த மாற்றம்'],
            'precautions': ['உட்காரவும் அல்லது படுக்கவும்', 'தண்ணீர் குடிக்கவும்', 'லேசான உணவு எடுத்துக்கொள்ளவும்', 'மெதுவாக எழுந்திருக்கவும்'],
            'next_steps': 'மயங்கி விழுதல், குழப்பம் அல்லது மீண்டும் மீண்டும் அறிகுறி இருந்தால் மருத்துவ உதவி பெறவும்.',
            'urgent': False,
        },
        'chest_pain': {
            'title': 'அவசர அறிகுறி இருக்கலாம்',
            'summary': 'நெஞ்சுவலி அல்லது மூச்சு சிரமம் தீவிரமாக இருக்கக்கூடும்.',
            'possible_causes': ['இதய பிரச்சனை', 'சுவாச சிரமம்', 'கடுமையான பதட்டம்'],
            'precautions': ['செயல்பாட்டை நிறுத்தவும்', 'நிமிர்ந்து உட்காரவும்', 'உடனே உதவி கேட்கவும்', 'வலி அதிகரித்தால் புறக்கணிக்காதீர்கள்'],
            'next_steps': 'வலி கடுமையாயிருந்தாலோ நீடித்தாலோ உடனடியாக அவசர மருத்துவ உதவி பெறவும்.',
            'urgent': True,
        },
        'emergency': {
            'title': 'அவசர மருத்துவ அறிகுறிகள்',
            'summary': 'உங்கள் உள்ளீட்டில் உடனடி கவனிப்பு தேவைப்படக்கூடிய அறிகுறிகள் உள்ளது.',
            'possible_causes': ['கடுமையான சுவாச பிரச்சனை', 'இதய தொடர்பான பிரச்சனை', 'மற்ற அவசர நிலை'],
            'precautions': ['அவசர உதவி எண்ணுக்கு அழைக்கவும்', 'தாமதிக்காதீர்கள்', 'பாதுகாப்பான நிலையில் உட்காரவும்/படுக்கவும்', 'அருகில் உள்ளவரிடம் உதவி கேட்கவும்'],
            'next_steps': 'தயவுசெய்து உடனடியாக அவசர மருத்துவ சேவையை அணுகவும்.',
            'urgent': True,
        },
        'general': {
            'title': 'பொது உடல்நல வழிகாட்டல்',
            'summary': 'துல்லியமாக கூற இன்னும் சில விவரங்கள் தேவை.',
            'possible_causes': ['லேசான நோய்', 'நீர்ச்சத்து குறைவு', 'தற்காலிக உடல் எரிச்சல்'],
            'precautions': ['முக்கிய அறிகுறியை எழுதுங்கள்', 'எத்தனை நாட்களாக உள்ளது கூறுங்கள்', 'காய்ச்சல்/வலி/மூச்சு சிரமம் இருந்தால் குறிப்பிடுங்கள்'],
            'next_steps': 'வலி எங்கு உள்ளது, எத்தனை நாட்களாக உள்ளது போன்ற கூடுதல் தகவலை வழங்குங்கள்.',
            'urgent': False,
        },
    },
    'hi': {
        'greeting': {
            'title': 'स्वागत है',
            'summary': 'अपने लक्षण, कितने समय से हैं, और कितनी गंभीरता है यह बताइए।',
            'possible_causes': ['अभी कोई लक्षण दर्ज नहीं हुआ'],
            'precautions': ['लक्षण साफ लिखें', 'अवधि बताएं', 'बुखार या सांस की तकलीफ हो तो जरूर बताएं'],
            'next_steps': 'अपने लक्षण लिखकर भेजें, मैं विश्लेषण करूँगा।',
            'urgent': False,
        },
        'fever': {
            'title': 'संभावित बुखार या वायरल संक्रमण',
            'summary': 'ये लक्षण बुखार या सामान्य वायरल बीमारी से मिलते-जुलते हैं।',
            'possible_causes': ['वायरल संक्रमण', 'सीजनल फ्लू', 'डिहाइड्रेशन'],
            'precautions': ['आराम करें', 'पर्याप्त पानी पिएं', 'तापमान मॉनिटर करें', 'बिना सलाह दवा न लें'],
            'next_steps': 'अगर बुखार 2 दिन से ज्यादा रहे या सांस की दिक्कत बढ़े तो डॉक्टर से मिलें।',
            'urgent': False,
        },
        'cough': {
            'title': 'खांसी से जुड़ा पैटर्न',
            'summary': 'इनपुट से खांसी या गले की समस्या का संकेत मिलता है।',
            'possible_causes': ['वायरल सर्दी', 'गले में जलन', 'एलर्जी'],
            'precautions': ['पानी ज्यादा पिएं', 'गले को आराम दें', 'धूल और धुएं से बचें', 'जरूरत हो तो मास्क पहनें'],
            'next_steps': 'खांसी ज्यादा बढ़े, एक हफ्ते से ज्यादा रहे, या सांस की दिक्कत हो तो डॉक्टर से सलाह लें।',
            'urgent': False,
        },
        'stomach_pain': {
            'title': 'पाचन संबंधी समस्या',
            'summary': 'लक्षण पेट या पाचन तंत्र की समस्या की ओर इशारा करते हैं।',
            'possible_causes': ['अपच', 'गैस्ट्रिक समस्या', 'हल्का फूड पॉइजनिंग'],
            'precautions': ['थोड़ा-थोड़ा पानी पिएं', 'हल्का भोजन लें', 'तला-भुना भोजन न लें', 'आराम करें'],
            'next_steps': 'दर्द तेज हो, लगातार रहे, या पानी न रुक पाए तो तुरंत डॉक्टर से मिलें।',
            'urgent': False,
        },
        'headache': {
            'title': 'सिरदर्द या डिहाइड्रेशन पैटर्न',
            'summary': 'ये लक्षण सिरदर्द, थकान या डिहाइड्रेशन से जुड़े हो सकते हैं।',
            'possible_causes': ['डिहाइड्रेशन', 'कम नींद', 'तनाव', 'आंखों पर जोर'],
            'precautions': ['पानी पिएं', 'शांत जगह पर आराम करें', 'स्क्रीन टाइम कम करें', 'अचानक खड़े न हों'],
            'next_steps': 'अगर सिरदर्द बहुत तेज हो, असामान्य हो, या उल्टी/दृष्टि समस्या हो तो डॉक्टर से जांच कराएं।',
            'urgent': False,
        },
        'dizziness': {
            'title': 'चक्कर या कमजोरी पैटर्न',
            'summary': 'इनपुट से चक्कर या कमजोरी का संकेत मिलता है।',
            'possible_causes': ['पानी की कमी', 'शुगर कम होना', 'थकान', 'ब्लड प्रेशर में बदलाव'],
            'precautions': ['बैठ जाएं या लेट जाएं', 'पानी पिएं', 'हल्का खाना लें', 'धीरे-धीरे उठें'],
            'next_steps': 'बेहोशी, भ्रम, या बार-बार चक्कर आए तो तुरंत चिकित्सा सहायता लें।',
            'urgent': False,
        },
        'chest_pain': {
            'title': 'संभावित आपात लक्षण',
            'summary': 'सीने में दर्द या सांस की तकलीफ गंभीर हो सकती है।',
            'possible_causes': ['हृदय संबंधी समस्या', 'श्वसन संकट', 'गंभीर चिंता'],
            'precautions': ['गतिविधि रोकें', 'सीधे बैठें', 'तुरंत मदद लें', 'दर्द बढ़े तो नजरअंदाज न करें'],
            'next_steps': 'अगर दर्द तेज या लगातार है तो तुरंत इमरजेंसी मेडिकल सहायता लें।',
            'urgent': True,
        },
        'emergency': {
            'title': 'आपातकालीन लक्षण',
            'summary': 'इनपुट में ऐसे संकेत हैं जिनके लिए तुरंत उपचार की जरूरत हो सकती है।',
            'possible_causes': ['गंभीर सांस संबंधी समस्या', 'हृदय संबंधी समस्या', 'अन्य आपात स्थिति'],
            'precautions': ['इमरजेंसी सेवा को कॉल करें', 'देरी न करें', 'सुरक्षित स्थिति में बैठें/लेटें', 'पास के व्यक्ति से मदद लें'],
            'next_steps': 'कृपया तुरंत आपातकालीन चिकित्सा सहायता प्राप्त करें।',
            'urgent': True,
        },
        'general': {
            'title': 'सामान्य स्वास्थ्य मार्गदर्शन',
            'summary': 'सही सलाह के लिए थोड़ी और जानकारी चाहिए।',
            'possible_causes': ['हल्की बीमारी', 'डिहाइड्रेशन', 'अस्थायी जलन'],
            'precautions': ['मुख्य लक्षण बताएं', 'अवधि बताएं', 'बुखार/दर्द/सांस की तकलीफ बताएं'],
            'next_steps': 'दर्द कहां है, कितने दिन से है, और कितनी गंभीरता है यह जोड़ें।',
            'urgent': False,
        },
    },
}

GENERAL_FOLLOW_UP = {
    'en': 'Please add the main symptom, how long it has lasted, and whether there is fever, pain, or breathing difficulty.',
    'ta': 'முக்கிய அறிகுறி என்ன, எத்தனை நாட்களாக உள்ளது, காய்ச்சல்/வலி/மூச்சுத்திணறல் உள்ளதா என்பதைச் சேர்க்கவும்.',
    'hi': 'कृपया मुख्य लक्षण, कितने समय से है, और बुखार/दर्द/सांस की तकलीफ है या नहीं यह बताएं।',
}